#!/bin/bash
# Railway Deployment Helper Script
# Run this BEFORE pushing to GitHub to generate your backend .env

set -e

echo "========================================="
echo "  CreditMatch.uk — Railway Setup Helper"
echo "========================================="
echo ""

# Generate JWT Secret
echo "🔐 Generating JWT_SECRET..."
JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
echo "✅ JWT_SECRET generated (copy this to Railway Variables):"
echo "   $JWT_SECRET"
echo ""

# Generate Admin Password
echo "🔑 Generating secure admin password..."
ADMIN_PASSWORD=$(node -e "console.log(require('crypto').randomBytes(16).toString('hex'))")
echo "✅ ADMIN_PASSWORD generated (copy this to Railway Variables):"
echo "   $ADMIN_PASSWORD"
echo ""

echo "========================================="
echo "  Railway Environment Variables"
echo "========================================="
echo ""
echo "Add these in Railway → Your Service → Variables:"
echo ""
echo "  DATABASE_URL           = <copy from your PostgreSQL service Variables tab>"
echo "  JWT_SECRET             = $JWT_SECRET"
echo "  ADMIN_PASSWORD         = $ADMIN_PASSWORD"
echo "  ADMIN_EMAIL            = admin@creditmatch.uk"
echo "  PORT                   = 4000"
echo "  NODE_ENV               = production"
echo "  JWT_EXPIRES_IN         = 7d"
echo "  FRONTEND_URL           = https://YOUR-VERCEL-URL.vercel.app"
echo "  RATE_LIMIT_WINDOW_MS   = 900000"
echo "  RATE_LIMIT_MAX_REQUESTS = 50"
echo "  ADMIN_EMAIL_TO         = your@email.com"
echo "  EASEYEARNS_URL         = https://easyearns.com"
echo ""

echo "========================================="
echo "  Vercel Environment Variables"
echo "========================================="
echo ""
echo "Add these in Vercel → Project Settings → Environment Variables:"
echo ""
echo "  NEXT_PUBLIC_API_URL      = https://YOUR-RAILWAY-URL.railway.app"
echo "  NEXT_PUBLIC_SITE_URL     = https://YOUR-VERCEL-URL.vercel.app"
echo "  NEXT_PUBLIC_EASEYEARNS_URL = https://easyearns.com"
echo ""

echo "========================================="
echo "  Next Steps"
echo "========================================="
echo ""
echo "1. Create PostgreSQL database in Railway"
echo "   → New Project → Create → PostgreSQL"
echo "   → Copy the DATABASE_URL from Variables tab"
echo ""
echo "2. Push to GitHub:"
echo "   git init && git add . && git commit -m 'Initial commit'"
echo "   git remote add origin https://github.com/YOUR-USERNAME/creditmatch.git"
echo "   git push -u origin main"
echo ""
echo "3. Deploy backend on Railway:"
echo "   → New Project → Deploy from GitHub"
echo "   → Select your repo"
echo "   → Set Root Directory to: backend"
echo "   → Build Command: npm install && npx prisma generate && npx prisma migrate deploy && npx prisma db seed"
echo "   → Start Command: npm start"
echo "   → Add all variables from above"
echo ""
echo "4. Deploy frontend on Vercel:"
echo "   → Import your GitHub repo"
echo "   → Root Directory: frontend"
echo "   → Add environment variables from above"
echo ""
echo "5. Verify:"
echo "   curl https://YOUR-RAILWAY-URL.railway.app/api/health"
echo ""
echo "========================================="
echo "  Admin Login (after deployment)"
echo "========================================="
echo ""
echo "  URL:      https://YOUR-VERCEL-URL.vercel.app/admin/login"
echo "  Email:    admin@creditmatch.uk"
echo "  Password: $ADMIN_PASSWORD"
echo ""
echo "⚠️  SAVE THIS PASSWORD — you won't see it again!"
echo ""
